### ISSUE TITLE
c2w_to_elu -> elu_to_c2w leads to inconsistent pose matrices

### ISSUE THREAD

**Issue by ponimatkin** [xt4d/id-pose#3]
Hi, I tried to do as you said to me in #1, however, if I do the check for the same pose, i.e. c2w_to_elu -> elu_to_c2w I get errors that are always close to ~180 degrees. Did you ever encounter any of those issues?

Thanks!

**Comment by xt4d** [comment]
Hi, 

Thanks for letting us know the issue.

This could be due to the incorrect direction of the look-at vector. Please try the ```c2w_to_elu``` function as follows:
```
def c2w_to_elu(c2w):

    w2c = np.linalg.inv(c2w)
    eye = c2w[:3, 3]
    lookat_dir = -w2c[2, :3] # fix the direction
    lookat = eye + lookat_dir
    up = w2c[1, :3]

    return eye, lookat, up
```

**Comment by ponimatkin** [comment]
Hi, sorry for late reply. This solved the issue, thanks!
