### ISSUE TITLE
Reconstruction of 3d model based on sparse multi view inputs

### ISSUE THREAD

**Issue by ghpkishore** [xt4d/id-pose#4]
Hi! I saw the recent tweet on the id-pose of the foosball table, and that you guys are working on releasing 3D reconstruction of the model. I wanted to know if you have any timelines on when we can post 4 to 6 pictures of a real world object so that we can get a 3D model of the object.

**Comment by xt4d** [comment]
Hello, thank you for your interest! 

Indeed, we are developing a new multi-view reconstruction model, but it's a separate project, and we don't have a release timeline for it yet. 

We noticed the tweets by Gradio that may have created some misunderstanding about our work. ID-Pose is a method for estimating camera poses. The foosball table displayed in the demo is not reconstructed, it is the ground truth used to visualize the precision of estimated camera poses.

If you are looking for a multi-view reconstruction model, I recommend checking out our recent work [InstantMesh](https://github.com/TencentARC/InstantMesh), which includes a model that takes several posed images to predict the 3D mesh of an object. Feel free to post any questions or issues about the model there. Thanks!

**Comment by ghpkishore** [comment]
Thank you. As you mentioned i was indeed confused about the gradio tweet.
