### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED

### ISSUE THREAD

**Issue by shirleyanan** [xt4d/id-pose#5]
Hey there, I was trying to run test_pose_estimation.py on RTX 3090Ti, but I encountered a RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED. Do you happen to know what could be causing this issue?

**Comment by xt4d** [comment]
Hi @shirleyanan, 

This error may result from various causes, such as an incorrect environment or GPU memory issues. Please refer to the following link for potential solutions:
https://stackoverflow.com/questions/66588715/runtimeerror-cudnn-error-cudnn-status-not-initialized-using-pytorch

I guess that the RTX3090 may not have sufficient GPU memory to run the back-propagation of the diffusion model (inversion process). The code was tested on a Tesla V100, and it consumed approximately 28GB of memory.

**Comment by shirleyanan** [comment]
Thank you for your response, I tried lowering the torch version and it seems to have fixed the issue. But yeah, like you said, the RTX3090 can't handle the full test, so I'll switch to using the V100 for testing.
